# Generated by Django 3.2.14 on 2023-01-09 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20230109_2104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='address',
            new_name='table_no',
        ),
    ]
